// Rebuild the embedded MCP factory from the pinned upstream npm package.
import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=dirname(fileURLToPath(import.meta.url));
const out=resolve(root,'../../pkg/pi/mcp.generated.ts');
const result=await build({entryPoints:[join(root,'entry.ts')],bundle:true,platform:'node',target:'node22',format:'esm',external:['@earendil-works/*'],outfile:out,metafile:true,minify:true,supported:{'template-literal':false},legalComments:'eof',banner:{js:'// Code generated by tools/pi-extension/build.mjs; DO NOT EDIT.\n// pi-mcp-adapter 2.32.1 and pi-auto-approval 0.1.0. Third-party licenses: MCP-LICENSES.txt.'}});
const licenses=new Map();
for (const name of Object.keys(result.metafile.inputs)) {
 let directory=dirname(resolve(name));
 while(directory!==dirname(directory)) {
  try {
   const pkg=JSON.parse(await readFile(join(directory,'package.json'),'utf8'));
   if(pkg.name && !licenses.has(pkg.name)) {
    let body='';
    for(const file of ['LICENSE','LICENSE.md','LICENSE.txt','license','license.md','COPYING']) {try{body=await readFile(join(directory,file),'utf8');break}catch{}}
    licenses.set(pkg.name,`${pkg.name}@${pkg.version} (${pkg.license ?? 'see package'})\n${body.replace(/[ \t]+$/gm,'')}`);
   }
   break;
  } catch {directory=dirname(directory)}
 }
}
await writeFile(resolve(root,'../../pkg/pi/MCP-LICENSES.txt'),[...licenses.values()].sort().join('\n\n--------------------\n\n'));
console.log(`Bundled ${licenses.size} packages into ${out}`);
